# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: |
         sudo apt-get purge firefox
         wget http://ftp.mozilla.org/pub/firefox/releases/59.0/linux-$(uname -m)/en-US/firefox-59.0.tar.bz2
         tar -xjf firefox-59.0.tar.bz2
         sudo mv /usr/bin/firefox /usr/bin/firefox_old
         sudo ln -s /opt/firefox/firefox /usr/bin/firefox

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mkdir test-reports

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean integration-test